metadata_root: "./data/dataset/metadata/dataset_root.json"
log_directory: "./log/latent_diffusion"
project: "drawspeech"
precision: "high"

variables:
  sampling_rate: &sampling_rate 22050
  mel_bins: &mel_bins 80
  latent_embed_dim: &latent_embed_dim 8
  latent_t_size: &latent_t_size 216 # TODO might need to change
  latent_f_size: &latent_f_size 20
  in_channels: &unet_in_channels 8
  optimize_ddpm_parameter: &optimize_ddpm_parameter true
  optimize_gpt: &optimize_gpt true
  warmup_steps: &warmup_steps 2000  # only works in LDM training

data: 
  train: ["ljspeech"]
  val: "ljspeech"
  test: "ljspeech"
  class_label_indices: null
  dataloader_add_ons: []

step:
  # val_check_interval: 5000
  validation_every_n_epochs: 2
  save_checkpoint_every_n_steps: 1000
  limit_val_batches: 2
  max_steps: 80000
  save_top_k: 1
  save_last: ture

preprocessing:
  audio:
    sampling_rate: *sampling_rate
    max_wav_value: 32768.0
    duration: 10.04
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: *mel_bins
    mel_fmin: 0
    mel_fmax: 8000
  preprocessed_data:
    energy: data/dataset/metadata/ljspeech/phoneme_level/energy
    pitch: data/dataset/metadata/ljspeech/phoneme_level/pitch
    duration: data/dataset/metadata/ljspeech/phoneme_level/duration

model:
    base_learning_rate: 8.0e-06
    target: drawspeech.modules.latent_encoder.autoencoder.AutoencoderKL
    params: 
      # reload_from_ckpt: "data/checkpoints/vae_mel_16k_64bins.ckpt"
      sampling_rate: *sampling_rate
      batchsize: 8
      monitor: val/rec_loss   # actually we use global_step
      image_key: fbank
      subband: 1
      embed_dim: *latent_embed_dim
      time_shuffle: 1
      lossconfig:
        target: drawspeech.losses.LPIPSWithDiscriminator
        params:
          disc_start: 50001
          kl_weight: 1000.0
          disc_weight: 0.5
          disc_in_channels: 1
      ddconfig: 
        double_z: true
        mel_bins: *mel_bins # The frequency bins of mel spectrogram
        z_channels: 8
        resolution: *latent_t_size
        downsample_time: false
        in_channels: 1
        out_ch: 1
        ch: 128 
        ch_mult:
        - 1
        - 2
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0
    